services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudticket-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cloudticket_user
      POSTGRES_PASSWORD: cloudticket_password
      POSTGRES_DB: cloudticket_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cloudticket-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
